### ISSUE TITLE
🐛 Discrepancy on report numbers

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#396] opened 2022-12-07 17:26 UTC
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
From the homepage I see 9 errors, but when I open the report it shows 8

### To Reproduce
1. Go to https://codeauditor.com/explore
2. Go to https://codeauditor.com/build/5b918414-229e-4e3f-8835-445c58d35401 
3. Compare numbers

### Tasks
- [ ] Investigate
- [ ] Fix

### Screenshots

<img width="1333" alt="Screen Shot 2022-12-07 at 9 23 59 AM" src="https://user-images.githubusercontent.com/12601228/206248590-79f3a52f-c9a7-4442-9f44-f04fe03b51db.png">

<img width="1327" alt="Screen Shot 2022-12-07 at 9 23 46 AM" src="https://user-images.githubusercontent.com/12601228/206248581-8c8ce92a-399e-45d1-b8b0-0556b6cec406.png">

Thanks!

**Comment by tombui99** [comment] 2022-12-17 07:30
Hi @tiagov8 
cc @adamcogan 

> Fix discrepancy on report numbers

Done - this was due to the enormous size of SSW Rules which impacts network during the scan and fluctuates the report numbers, I have fixed it by adding more threshold to the scan so now it is getting more consistent

![image](https://user-images.githubusercontent.com/67776356/208230998-5ffb9c1b-e4c0-4465-a983-5b966d4f27c1.png)

![image](https://user-images.githubusercontent.com/67776356/208231020-49482778-206f-463e-936c-4745ffd5ea40.png)

**Figure: Consistent report numbers**

**Comment by tombui99** [comment] 2023-03-30 06:38
Hi @tiagov8 
CC @adamcogan 

Closing as issue has been resolved

**Comment by tiagov8** [comment] 2023-04-04 19:57
Hey @tombui99 

(reopening as the latest report has this bug)

If you look at https://codeauditor.com/explore
...you see 28 bad links

Then look at https://codeauditor.com/build/a012dfc3-bdda-4a45-eba5-03b34ea15c9a
...you see 17 errors

- [ ] Please investigate and fix
- [ ] Please make both labels consistent by changing them to be "**Bad Links (404)**"

---

### Screenshots

<img width="1338" alt="Screenshot 2023-04-04 at 4 53 19 PM" src="https://user-images.githubusercontent.com/12601228/229905263-bebd1713-e5ad-4d2d-b3a4-ec50037265c2.png">


<img width="1000" alt="Screenshot 2023-04-04 at 4 55 35 PM" src="https://user-images.githubusercontent.com/12601228/229905463-6b487e57-ab94-4847-92f6-8adaff8e1b6e.png">

**Comment by tombui99** [comment] 2023-04-13 06:25
Hi @tiagov8 
CC @adamcogan 

> Please investigate and fix

Done - This inaccurate reporting has been caused by a depreciated library that we used to query data from Azure Storage which did not return all the columns correctly. I have updated to use the new library and this inconsistency no longer exists.

![image](https://user-images.githubusercontent.com/67776356/231654861-ad761430-0935-40c8-b759-52d5f2da289b.png)

**Figure: Deprecated azure-storage library**

![image](https://user-images.githubusercontent.com/67776356/231671724-f25fc52a-49e1-47c0-b8c9-79b468d2d125.png)
![image](https://user-images.githubusercontent.com/67776356/231671779-1aef0f86-f08c-4996-8330-00829ca3866d.png)

**Figure: Consistent report numbers across the pages**

**Comment by tombui99** [comment] 2023-04-17 04:12
Hi @tiagov8 
CC @adamcogan @william-liebenberg 

Closing as issue has been resolved

**Closed** 2023-04-17 04:11 UTC
Labels: type: bug
